# Generated by Django 4.0 on 2022-01-04 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=12)),
                ('telephone', models.CharField(max_length=12)),
                ('type_of_shelter', models.CharField(choices=[('General', 'General Shelter'), ('Gender/Age Restrictions', 'Gender and Age Restrictions'), ("Men's", "Men's Shelters"), ("Women's", "Women's Shelters"), ('Women and Kids', "Women's and Children's Shelters"), ('Teens', 'Teenage Shelters'), ('Seniors', 'Senior Citizens Shelters'), ('Families', 'Family Shelters'), ('Long-Term', 'Transitional Emergency Long-Term Supportive Housing'), ('Emergency', 'Emergency Shelter')], default='General Shelter', max_length=50)),
                ('shelter_services', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
